services:
  api:
    build: .
    container_name: aegis_gateway_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis_vault 
    depends_on:
      - redis_vault
    networks:
      - aegis_net

  redis_vault:
    image: redis:7.2-alpine
    container_name: gateway_redis_vault
    command: redis-server --save "" --appendonly no
    networks:
      - aegis_net

networks:
  aegis_net:
    driver: bridge