name: Aegis Gateway CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build and Spin Up Stack
      run: |
        
        echo "LLM_MODEL=tinyllama" >> .env
        echo "LLM_API_KEY=fake_api_key" >> .env
        echo "VAULT_ENCRYPTION_KEY=32_character_base64_string_placeholder=" >> .env 
        docker compose up -d --build
        
        sleep 10

        docker compose ps
        docker compose logs api

    - name: Pull Model Into Docker Container
      run: |
        docker compose exec -T ollama_server ollama pull tinyllama

    - name: Run Integration Tests
      run: |
        docker compose exec -T api pytest -v

    - name: Teardown Stack
      if: always()
      run: |
        docker compose down -v

